#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: Neo Evolutionary Logic Project
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  To activate the fusion of neo evolutionary logic will be to create new frontiers by honoring our past and marrying it with the ideas of the future; where atop the shoulders of our wise ancestral giants that have come before us, may we stand and see the roads ahead with great clarity and virtue
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  Neo Evolutionary Logic Project
  N.Ev.Lo. Project is a 501 (c) 3 Organization

  Origin Story: The Dream Seed

    This movement was and shall remain to be known as the Neo Evolutionary Logic Project (NEVLO Project). Inspired greatly by the arts of antiquity, the word neo derives from the Greek word neos, which means new; giving us yet another way to phrase something familiar as something different. It is from the very root of this movement's title that language, history, creation have a platform for which to teach us new ways of activating our artful-logic. Hand in hand, logic is the idea preceding creation; for what can be thought may then be transmuted into being --  an artful manifestation by any one creator or creators. By keenly observing our past, we are able to build diligently and conceive more efficient, more evolved ways to thrive and ally ourselves with all things in existence. Thus begets the idea of neo evolution where we pay homage to older systems of logic and build forward with honor and integrity in order to truly become something not only revolutionary but artfully connected to every generation that has come before us. Art will forever represent the infinite potential of expression by any one creator or creators. Henceforth, to activate the fusion of neo evolutionary logic will be to create new frontiers by honoring our past and marrying them with the ideas of the future; where atop the shoulders of our wise ancestral giants that have come before us, may we stand and see the roads ahead with great clarity and virtue… And so the dream was born, giving way for one creator to become a team of co-creators; hoping to establish a residence on this planet that not only serves each other but our communities, our planet, and every generation to come.

  Where We're Headed ~ 2024 & Beyond

    Imagine renewably-powered library kiosks all around the world, shaped by a central tree growing out of the oculus of a geodesic dome, surrounded by the edible garden walls of a meditation labyrinth. Each kiosk connected to each other while being particularly unique in their reports of the local bioregion.

    Imagine a regenerative-minded, social permaculture circus that allows those to play the consciousness, lifeskills video game or the in-person interactive labyrinth obstacle course, The Labyrinth Artnasium; overlayed by the decorum of the Armone Galaxy ethos and language, which informs the architectural and interior forms of everything a visitor experiences and interacts with.

#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: connect@neverendinglogic.com
org_street_address: 905 6th Street #Please include suite number on the line below
org_address_suite:
org_city: Arcata
org_state: CA
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  95521
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  (707) 572 - 5289

#SOCIAL MEDIA
org_twitter_username: nevloproject
org_facebook_username: nevloproject
org_instagram_username: nevloproject

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
is_501c3: true

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name:
tinyletter_username:

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: true

#COLOR SCHEME
#Select one of the five color schemes (default, one, two, three, or four)
color_scheme: four

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
